enum Action {
  GET_ISSUES = 'GET_ISSUES',
  GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS',
  GET_ISSUES_ERROR = 'GET_ISSUES_ERROR',

  UPDATE_ISSUE = 'UPDATE_ISSUE',
  TOGGLE_LOCK_ISSUE = 'TOGGLE_LOCK_ISSUE',
  UPDATE_ISSUE_SUCCESS = 'UPDATE_ISSUE_SUCCESS',

  REPORT_TASK = 'REPORT_TASK',

  TOGGLE_FORM = 'TOGGLE_FORM',
  TOGGLE_ISSUE = 'TOGGLE_ISSUE',
  TOGGLE_ERROR = 'TOGGLE_ERROR',
}

export default Action;
